### ISSUE TITLE
Error code 13: 

### ISSUE THREAD

**Issue by TheLaw1473** [covid-be-app/cwa-app-ios#270] opened 2020-10-21 01:49 UTC
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronalert.be)
* [ ] Bug is not already reported in another issue

## Describe the bug

I have updated to the newest version of Coronalert (1.1.1) on IOS 14.2 beta 3. I am getting the "error 13" code and it says I need to try again in 24 hours. However, I still got the "unknown risk" while I've been using it for 5 days. It has done a lot of exposure loggings. But all of them (since the ios 14.2 beta 3 update) have no new files the last one with. I am aware of the post that had "Error 2" and I've read that that was a fault on Apple's side and would be fixed in ios 14.2GM. I don't know if this is caused by the same fault but I just wanted to give you guys a heads up. 

## Expected behavior

Not seeing this error, and producing a risk report. 

## Steps to reproduce the issue

Open the app and it should give you this error code. 
![image](https://user-images.githubusercontent.com/26824871/96661996-b41ad900-134d-11eb-8adb-be80d3fd0309.png)
![image](https://user-images.githubusercontent.com/26824871/96662025-bed56e00-134d-11eb-9b8b-088749dae4a4.png)
![image](https://user-images.githubusercontent.com/26824871/96662038-c563e580-134d-11eb-96ac-6581e3bb2717.png)
![image](https://user-images.githubusercontent.com/26824871/96662080-ddd40000-134d-11eb-8c17-dc4a2b5ebdef.png)

## Technical details

- iOS Version: IOS 14.2 beta 3
- Device: iPhone XS
PS: Like the person on Error 2 said, I know you don't support Ios beta releases but I wanted to give you a heads up.
## Additional context
After receiving the "Error 2" I thought it was just my app so I deleted it and redownloaded it. that's why I only have 5 active days but the risk rapport says it isn't on long enough.

**Comment by ir-fuel** [comment] 2020-10-21 09:32
The problem is related to error 2.
Let me try to explain:
Error 13 = rate limiting (we can only call the API X times / day)
Error 2 = Exposure logging not successful

So what happens, the app retries multiple times, until it hits the rate limit, leading to error 13.

**Comment by JensTimmerman** [comment] 2020-10-23 15:05
I had this same issue, but this was fixed in latest ios update.

**Closed** 2020-10-28 16:13 UTC
Labels: bug
