### ISSUE TITLE
Date of last check 19-01-22 on Monday 24-01-22, i.e. 5 days ago.

### ISSUE THREAD

**Issue by Eleuthere** [covid-be-app/cwa-app-ios#453] opened 2022-01-24 10:36 UTC
Apple iPhone 8 iOS 14.8.1.
When I check the exposure today, I get a result from 5 days ago, and it takes ages and retries to get it.
Thanks.

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronalert.be)
* [ ] Bug is not already reported in another issue

## Describe the bug

 I get the exposure as of 5 days ago.

## Expected behaviour

 Exposure as of today.

## Steps to reproduce the issue

 Just open the app and wait.

## Technical details

- iOS Version: 14.8.1
- Device: iPhone 8

## Possible Fix

 From my experience it could be anything: network latency, bad database design, insufficient working memory, space leaks in a functional programming language, inefficient garbage collector, you name it.
Thanks.

**Comment by ir-fuel** [comment] 2022-01-24 10:39
This should be fixed in 1.11.1 which is supposed to go live any time soon.

The problem is that there is a 60 second timeout in the exposure notification check routine. Because of the huge amount of keys due to Omicron the device needs more than 60 seconds to proces them. The timeout has been pushed up to 4 minutes.

Fix is here:

https://github.com/covid-be-app/cwa-app-ios/pull/450/commits/944ffcaf2001d16e9b3f9e804e4a099fe8286950

**Closed as completed by ir-fuel** 2022-01-24 10:39 UTC
Labels: bug
