### ISSUE TITLE
Error (code 2) when showing homescreen 

### ISSUE THREAD

**Issue by samvandamme** [covid-be-app/cwa-app-ios#263] opened 2020-10-17 10:11 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronalert.be)
* [x] Bug is not already reported in another issue

## Describe the bug

Getting error alert every time I open up the homescreen. Even when I tap to go to any secondary screen, go back to the homescreen, it shows up.
What might help: The "Updated" information (see screenshot) with the timestamp doesn't change anymore since I received the error for the first time.

## Expected behaviour

Not seeing this error.

## Steps to reproduce the issue

Just opening up the app shows me the following error:
![IMG_5941](https://user-images.githubusercontent.com/7536195/96334489-7aa64d00-1071-11eb-9dc3-5765fc0f9bf4.png)

## Technical details

*Disclaimer:* I know you don't support iOS beta releases, but this is just a heads up for when it's released.
- iOS Version: 14.2 beta
- Device: iPhone X

**Comment by ir-fuel** [comment] 2020-10-17 22:44
Thanks for reporting!

We can reproduce the error on an iOS 14.2 Beta 3 device running the latest build, and we will look into the cause.

**Comment by ir-fuel** [comment] 2020-10-17 22:59
The German app (on which ours is based) has the same issue. They have investigated it and apparently it's a problem on Apple's side:

https://github.com/corona-warn-app/cwa-app-ios/issues/1339#issuecomment-709230027

**Comment by franklouwers** [comment] 2020-10-19 12:31
FYI: Apple Radar number 70404886 was filed for this issue.

**Comment by ir-fuel** [comment] 2020-10-19 15:21
We have also confirmation from Apple that this will be resolved in 14.2 GM

**Closed** 2020-10-21 09:38 UTC
Labels: bug
